server:
  port: 9096
spring :
  datasource :
    url: "jdbc:postgresql://localhost:5432/manavidyalayam"  
    username: postgres  
    password: admin
  jpa:
    properties :
      hibernate :
        default_schema : manavidyalayam
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto : update
